# fly.toml app configuration file generated for trouw-lisa-marino on 2025-02-12T20:19:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trouw-lisa-marino'
primary_region = 'ams'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app:app']

[[vm]]
  size = 'shared-cpu-1x'
